### PR TITLE
New handler format

### PR DESCRIPTION
**Pull request by y0no**
Change the way that the bridge handle template.
Add all the webhook handlers from bitbucket.

### CODE REVIEW

**Comment by danielkappelle** [comment]
Wow, you sure put in some effort! Nice work, I'll have to try it out later, but I'll merge it for now :)

**Comment by y0no** [comment]
Yep I hope you will like my modifications. I have two new commits on my master branch that improve templates if you want to merge them too (I have switched to master by mistake) .

**Comment by danielkappelle** [comment]
sure do like them (to be honest, I don't personally use this tool anymore..)

I can merge if you want

**Comment by y0no** [comment]
Yep I think this is a good way to handle all events.

**Pull request merged**
